-- ============================================================
-- 이용 종료(end_time) 경과 예약 자동 처리 (pg_cron / Edge Function)
--
-- 1) auto_return_expired_reservations — DB RPC
--    · confirmed + 미대여(rental_started_at IS NULL) + 종료 경과 → completed + is_no_show (환불 없음)
--    · in_use + 종료 경과 → returned (return_type = auto)
-- 2) scheduled-auto-return Edge Function — RPC 실행 + 노쇼 푸시 발송 (cron 권장)
-- 3) auto_complete_expired_reservations_for_me — 로그인 사용자 (앱 새로고침)
-- ============================================================

-- 마이그레이션 적용: supabase/migrations/20260628290000_auto_no_show_processing.sql

-- pg_cron — 매일 03:00 KST (18:00 UTC) 권장
-- create extension if not exists pg_cron with schema pg_catalog;
--
-- select cron.unschedule(jobid)
-- from cron.job
-- where jobname = 'daily-auto-return-expired-reservations';
--
-- Edge Function (노쇼 푸시 포함):
-- select cron.schedule(
--   'daily-auto-return-expired-reservations',
--   '0 18 * * *',
--   $$
--   select net.http_post(
--     url := 'https://<project-ref>.supabase.co/functions/v1/scheduled-auto-return',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer <SERVICE_ROLE_KEY>'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
--
-- RPC만 실행 (푸시 없음):
-- select cron.schedule(
--   'daily-auto-return-expired-reservations',
--   '0 18 * * *',
--   $$ select public.auto_return_expired_reservations(); $$
-- );
